document.querySelector('input[name="name"]').value = 'عيادة الدكتور سمير';
document.querySelector('input[name="name_ar"]').value = 'عيادة الدكتور سمير';
document.querySelector('input[name="slug"]').value = 'clinic-samer';
document.querySelector('input[name="contact_email"]').value = 'samer@clinic.com';
document.querySelector('input[name="contact_phone"]').value = '0599123456';
document.querySelector('select[name="product_profile"]').value = 'private_doctor_clinic';
document.querySelector('select[name="subscription_type"]').value = 'monthly';
document.querySelector('input[name="subscription_end"]').value = '2027-06-20';
document.querySelector('select[name="storage_mode"]').value = 'cloud';
'Form filled OK';
