[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra
filterwarnings =
    ignore::sqlalchemy.exc.LegacyAPIWarning

[coverage:run]
source =
    app
    routes
    services
    models
    utils
omit =
    */migrations/*
    */tests/*
    */__pycache__/*
    */venv/*
    */mockups/*

[coverage:report]
precision = 1
show_missing = false
skip_covered = true
fail_under = 0
