"""نظام كامل مع جميع الحقول

Revision ID: ff905b8f2982
Revises: 
Create Date: 2025-10-12 23:11:59.183285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff905b8f2982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('head_doctor_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_patients', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('capacity >= 0', name='chk_department_capacity_non_negative'),
    sa.ForeignKeyConstraint(['head_doctor_id'], ['users.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index('idx_department_active', ['is_active'], unique=False)
        batch_op.create_index('idx_department_name_ar', ['name_ar'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_head_doctor_id'), ['head_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_updated_at'), ['updated_at'], unique=False)

    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_companies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_companies_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_insurance_companies_updated_at'), ['updated_at'], unique=False)

    op.create_table('insurance_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('coverage_percentage', sa.Float(), nullable=True),
    sa.Column('max_coverage_amount', sa.Float(), nullable=True),
    sa.Column('requires_authorization', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('coverage_percentage >= 0 AND coverage_percentage <= 100', name='chk_coverage_percentage'),
    sa.CheckConstraint('max_coverage_amount >= 0', name='chk_max_coverage_amount'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_providers', schema=None) as batch_op:
        batch_op.create_index('idx_insurance_active', ['is_active'], unique=False)
        batch_op.create_index('idx_insurance_code', ['code'], unique=False)
        batch_op.create_index('idx_insurance_name', ['name'], unique=False)
        batch_op.create_index('idx_insurance_name_ar', ['name_ar'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('drug_interactions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('price >= 0', name='chk_medication_price'),
    sa.CheckConstraint('stock_quantity >= 0', name='chk_medication_stock'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index('idx_medication_active', ['is_active'], unique=False)
        batch_op.create_index('idx_medication_generic_name', ['generic_name'], unique=False)
        batch_op.create_index('idx_medication_trade_name', ['trade_name'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('first_name_ar', sa.String(length=80), nullable=True),
    sa.Column('last_name_ar', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('idx_patient_name', ['first_name', 'last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_national_id'), ['national_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_updated_at'), ['updated_at'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('USER_MANAGEMENT', 'PATIENT_MANAGEMENT', 'MEDICAL_RECORDS', 'FINANCIAL', 'SYSTEM_ADMIN', 'BACKUP_RESTORE', 'REPORTS', 'SETTINGS', 'SECURITY', 'AUDIT', name='permissioncategory'), nullable=False),
    sa.Column('level', sa.Enum('READ', 'WRITE', 'DELETE', 'ADMIN', 'SUPER_ADMIN', name='permissionlevel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('insurance_price', sa.Float(), nullable=True),
    sa.Column('cash_price', sa.Float(), nullable=True),
    sa.Column('vip_price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requires_doctor', sa.Boolean(), nullable=True),
    sa.Column('requires_department', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("service_type IN ('consultation', 'lab_test', 'radiology_scan', 'medication', 'procedure', 'emergency', 'other')", name='chk_service_type'),
    sa.CheckConstraint('base_price >= 0', name='chk_service_base_price'),
    sa.CheckConstraint('cash_price >= 0', name='chk_service_cash_price'),
    sa.CheckConstraint('insurance_price >= 0', name='chk_service_insurance_price'),
    sa.CheckConstraint('vip_price >= 0', name='chk_service_vip_price'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_prices', schema=None) as batch_op:
        batch_op.create_index('idx_service_active', ['is_active'], unique=False)
        batch_op.create_index('idx_service_code', ['service_code'], unique=False)
        batch_op.create_index('idx_service_effective', ['effective_from', 'effective_to'], unique=False)
        batch_op.create_index('idx_service_name', ['service_name'], unique=False)
        batch_op.create_index('idx_service_type', ['service_type'], unique=False)

    op.create_table('system_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(username) >= 3', name='chk_user_username_len'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_role', ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'starts_at', name='uq_appointment_patient_time')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('idx_appt_doctor_time', ['doctor_id', 'starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_updated_at'), ['updated_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("action IN ('create', 'update', 'delete', 'view', 'login', 'logout', 'export', 'import', 'backup', 'restore')", name='chk_action'),
    sa.CheckConstraint("entity_type IN ('user', 'patient', 'visit', 'appointment', 'payment', 'invoice', 'lab_test', 'radiology_test', 'notification', 'role', 'department')", name='chk_entity_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_trails', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)

    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_name', sa.String(length=200), nullable=False),
    sa.Column('backup_type', sa.String(length=50), nullable=False),
    sa.Column('backup_size', sa.BigInteger(), nullable=True),
    sa.Column('backup_path', sa.String(length=500), nullable=False),
    sa.Column('backup_status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('backup_notes', sa.Text(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('schedule_type', sa.String(length=50), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('next_backup', sa.DateTime(), nullable=True),
    sa.Column('restore_count', sa.Integer(), nullable=True),
    sa.Column('last_restore', sa.DateTime(), nullable=True),
    sa.Column('last_restore_by', sa.Integer(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('encryption_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.CheckConstraint("backup_status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED')", name='chk_backup_status'),
    sa.CheckConstraint("backup_type IN ('full', 'incremental', 'differential')", name='chk_backup_type'),
    sa.CheckConstraint("schedule_type IN ('daily', 'weekly', 'monthly', 'custom')", name='chk_schedule_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_restore_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index('idx_backup_created', ['created_at'], unique=False)
        batch_op.create_index('idx_backup_name', ['backup_name'], unique=False)
        batch_op.create_index('idx_backup_scheduled', ['is_scheduled'], unique=False)
        batch_op.create_index('idx_backup_status', ['backup_status'], unique=False)
        batch_op.create_index('idx_backup_type', ['backup_type'], unique=False)

    op.create_table('branding_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('organization_name_en', sa.String(length=200), nullable=True),
    sa.Column('organization_address', sa.Text(), nullable=True),
    sa.Column('organization_phone', sa.String(length=50), nullable=True),
    sa.Column('organization_email', sa.String(length=100), nullable=True),
    sa.Column('organization_website', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('favicon_path', sa.String(length=500), nullable=True),
    sa.Column('watermark_path', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('report_header_html', sa.Text(), nullable=True),
    sa.Column('report_footer_html', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('consultation_price', sa.Float(), nullable=False),
    sa.Column('follow_up_price', sa.Float(), nullable=True),
    sa.Column('emergency_price', sa.Float(), nullable=True),
    sa.Column('vip_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('consultation_price >= 0', name='chk_doctor_consultation_price'),
    sa.CheckConstraint('emergency_price >= 0', name='chk_doctor_emergency_price'),
    sa.CheckConstraint('follow_up_price >= 0', name='chk_doctor_follow_up_price'),
    sa.CheckConstraint('vip_price >= 0', name='chk_doctor_vip_price'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_pricing', schema=None) as batch_op:
        batch_op.create_index('idx_doctor_pricing_active', ['is_active'], unique=False)
        batch_op.create_index('idx_doctor_pricing_department', ['department_id'], unique=False)
        batch_op.create_index('idx_doctor_pricing_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('idx_doctor_pricing_effective', ['effective_from', 'effective_to'], unique=False)

    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_updated_at'), ['updated_at'], unique=False)

    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('recipient_role', sa.String(length=50), nullable=True),
    sa.Column('recipient_department_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nurses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('online_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('visit_type', sa.String(length=20), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confirmation_code', sa.String(length=10), nullable=True),
    sa.Column('is_new_patient', sa.Boolean(), nullable=True),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('insurance_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('no_show_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_table('patient_visit_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_visit_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_visit_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_visit_counters_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_visit_counters_updated_at'), ['updated_at'], unique=False)

    op.create_table('pricing_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('service_name_ar', sa.String(length=200), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('insurance_coverage', sa.Float(), nullable=True),
    sa.Column('patient_share', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("service_type IN ('consultation', 'lab', 'radiology', 'medication', 'other')", name='chk_pricing_service_type'),
    sa.CheckConstraint('base_price >= 0', name='chk_pricing_base_price'),
    sa.CheckConstraint('insurance_coverage >= 0 AND insurance_coverage <= 100', name='chk_pricing_insurance_coverage'),
    sa.CheckConstraint('patient_share >= 0', name='chk_pricing_patient_share'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_catalog', schema=None) as batch_op:
        batch_op.create_index('idx_pricing_active', ['is_active'], unique=False)
        batch_op.create_index('idx_pricing_service_type', ['service_type'], unique=False)
        batch_op.create_index('idx_pricing_temporary', ['is_temporary'], unique=False)

    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('condition_value', sa.String(length=100), nullable=False),
    sa.Column('condition_operator', sa.String(length=20), nullable=True),
    sa.Column('price_adjustment_type', sa.String(length=20), nullable=True),
    sa.Column('price_adjustment_value', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('max_queue_size', sa.Integer(), nullable=True),
    sa.Column('average_wait_time', sa.Integer(), nullable=True),
    sa.Column('emergency_priority', sa.Boolean(), nullable=True),
    sa.Column('force_entry_allowed', sa.Boolean(), nullable=True),
    sa.Column('payment_required', sa.Boolean(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('emergency_payment_waived', sa.Boolean(), nullable=True),
    sa.Column('auto_notifications', sa.Boolean(), nullable=True),
    sa.Column('notification_interval', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('template_variables', sa.Text(), nullable=True),
    sa.Column('page_size', sa.String(length=20), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('margins', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('grouping', sa.String(length=100), nullable=True),
    sa.Column('sorting', sa.String(length=100), nullable=True),
    sa.Column('chart_type', sa.String(length=50), nullable=True),
    sa.Column('display_format', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='unique_role_permission')
    )
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("event_type IN ('login_failed', 'password_changed', 'permission_denied', 'suspicious_activity', 'data_breach', 'unauthorized_access')", name='chk_event_type'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='chk_severity'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index('idx_security_created', ['created_at'], unique=False)
        batch_op.create_index('idx_security_event_type', ['event_type'], unique=False)
        batch_op.create_index('idx_security_resolved', ['is_resolved'], unique=False)
        batch_op.create_index('idx_security_severity', ['severity'], unique=False)
        batch_op.create_index('idx_security_user', ['user_id'], unique=False)

    op.create_table('service_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emergency_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('insurance_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_master_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_master_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_master_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_master_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_master_updated_at'), ['updated_at'], unique=False)

    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("category IN ('general', 'security', 'notification', 'backup', 'system', 'database', 'email', 'sms')", name='chk_category'),
    sa.CheckConstraint("config_type IN ('string', 'integer', 'boolean', 'json', 'file', 'password')", name='chk_config_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index('idx_config_category', ['category'], unique=False)
        batch_op.create_index('idx_config_key', ['config_key'], unique=False)
        batch_op.create_index('idx_config_system', ['is_system'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('log_category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("log_category IN ('authentication', 'database', 'payment', 'notification', 'system', 'security', 'performance')", name='chk_log_category'),
    sa.CheckConstraint("log_level IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')", name='chk_log_level'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index('idx_log_category', ['log_category'], unique=False)
        batch_op.create_index('idx_log_created', ['created_at'], unique=False)
        batch_op.create_index('idx_log_level', ['log_level'], unique=False)
        batch_op.create_index('idx_log_user', ['user_id'], unique=False)

    op.create_table('temporary_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('service_name_ar', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('price >= 0', name='chk_temporary_service_price'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temporary_services', schema=None) as batch_op:
        batch_op.create_index('idx_temporary_service_active', ['is_active'], unique=False)
        batch_op.create_index('idx_temporary_service_name', ['service_name'], unique=False)

    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='unique_user_permission')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('visit_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=True),
    sa.Column('receipt_printed', sa.Boolean(), nullable=True),
    sa.Column('visit_type', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('is_force_payment', sa.Boolean(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('prescription_issued', sa.Boolean(), nullable=True),
    sa.Column('lab_tests_ordered', sa.Boolean(), nullable=True),
    sa.Column('radiology_ordered', sa.Boolean(), nullable=True),
    sa.Column('card_number_last_digits', sa.String(length=4), nullable=True),
    sa.Column('card_holder_name', sa.String(length=100), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_coverage_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('insurance_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('patient_share', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('force_payment_reason', sa.Text(), nullable=True),
    sa.Column('force_payment_approved_by', sa.Integer(), nullable=True),
    sa.Column('force_payment_approved_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_printed_by', sa.Integer(), nullable=True),
    sa.Column('receipt_printed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('archived_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['force_payment_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_printed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_number')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index('idx_visit_department_status', ['department_id', 'status'], unique=False)
        batch_op.create_index('idx_visit_doctor_status', ['doctor_id', 'status'], unique=False)
        batch_op.create_index('idx_visit_patient_created', ['patient_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_updated_at'), ['updated_at'], unique=False)

    op.create_table('backup_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("log_type IN ('info', 'warning', 'error', 'success', 'debug')", name='chk_log_type'),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_logs', schema=None) as batch_op:
        batch_op.create_index('idx_backup_log_backup', ['backup_id'], unique=False)
        batch_op.create_index('idx_backup_log_created', ['created_at'], unique=False)
        batch_op.create_index('idx_backup_log_type', ['log_type'], unique=False)

    op.create_table('emergency_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('triage_notes', sa.Text(), nullable=True),
    sa.Column('vital_signs', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='IN_PROGRESS', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_cases_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_cases_updated_at'), ['updated_at'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('paid_amount >= 0', name='chk_invoice_paid_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='chk_invoice_total_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('idx_invoice_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_visit_id'), ['visit_id'], unique=False)

    op.create_table('lab_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('request_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_request_number'), ['request_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_lab_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_visit_id'), ['visit_id'], unique=False)

    op.create_table('medical_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('signed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_visit_id'), ['visit_id'], unique=False)

    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('online_booking_payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['online_bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('prescription_number', sa.String(length=50), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'dispensed', 'cancelled')", name='chk_prescription_status'),
    sa.CheckConstraint('total_cost >= 0', name='chk_prescription_total_cost'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_number')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index('idx_prescription_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('idx_prescription_number', ['prescription_number'], unique=False)
        batch_op.create_index('idx_prescription_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_prescription_status', ['status'], unique=False)
        batch_op.create_index('idx_prescription_visit', ['visit_id'], unique=False)

    op.create_table('pricing_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('emergency_price', sa.Float(), nullable=True),
    sa.Column('insurance_price', sa.Float(), nullable=True),
    sa.Column('private_price', sa.Float(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('tax_percentage', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('queue_number', sa.String(length=20), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('emergency_reason', sa.Text(), nullable=True),
    sa.Column('emergency_approved_by', sa.Integer(), nullable=True),
    sa.Column('force_entry', sa.Boolean(), nullable=True),
    sa.Column('force_entry_reason', sa.Text(), nullable=True),
    sa.Column('force_entry_approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['emergency_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['force_entry_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radiology_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('request_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('modality', sa.String(length=20), nullable=True),
    sa.Column('body_part', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radiology_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radiology_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_requests_request_number'), ['request_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_radiology_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_requests_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_requests_visit_id'), ['visit_id'], unique=False)

    op.create_table('report_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=False),
    sa.Column('execution_parameters', sa.Text(), nullable=True),
    sa.Column('execution_filters', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('result_file_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('oxygen_saturation', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('claim_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_claim', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['insurance_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_claims_claim_number'), ['claim_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_insurance_claims_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_visit_id'), ['visit_id'], unique=False)

    op.create_table('invoice_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='chk_line_qty_positive'),
    sa.CheckConstraint('total_price >= 0', name='chk_line_total_price_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='chk_line_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_services_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_services_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_services_service_code'), ['service_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_services_visit_id'), ['visit_id'], unique=False)

    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('reference_range', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['lab_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_test_code'), ['test_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_updated_at'), ['updated_at'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='chk_payment_amount_non_negative'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_payment_invoice_created', ['invoice_id', 'created_at'], unique=False)
        batch_op.create_index('idx_payment_method', ['method'], unique=False)
        batch_op.create_index('idx_payment_patient_date', ['patient_id', 'payment_date'], unique=False)
        batch_op.create_index('idx_payment_status', ['status'], unique=False)
        batch_op.create_index('idx_payment_visit_date', ['visit_id', 'payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_received_by'), ['received_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_visit_id'), ['visit_id'], unique=False)

    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='chk_prescription_item_quantity'),
    sa.CheckConstraint('total_price >= 0', name='chk_prescription_item_total_price'),
    sa.CheckConstraint('unit_price >= 0', name='chk_prescription_item_unit_price'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.create_index('idx_prescription_item_medication', ['medication_id'], unique=False)
        batch_op.create_index('idx_prescription_item_prescription', ['prescription_id'], unique=False)

    op.create_table('radiology_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('study_uid', sa.String(length=64), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('impression', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['radiology_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radiology_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radiology_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_results_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_results_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_results_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_results_study_uid'), ['study_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_results_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radiology_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radiology_results_updated_at'))
        batch_op.drop_index(batch_op.f('ix_radiology_results_study_uid'))
        batch_op.drop_index(batch_op.f('ix_radiology_results_status'))
        batch_op.drop_index(batch_op.f('ix_radiology_results_request_id'))
        batch_op.drop_index(batch_op.f('ix_radiology_results_patient_id'))
        batch_op.drop_index(batch_op.f('ix_radiology_results_created_at'))

    op.drop_table('radiology_results')
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index('idx_prescription_item_prescription')
        batch_op.drop_index('idx_prescription_item_medication')

    op.drop_table('prescription_items')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_visit_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_received_by'))
        batch_op.drop_index(batch_op.f('ix_payments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_payments_method'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index('idx_payment_visit_date')
        batch_op.drop_index('idx_payment_status')
        batch_op.drop_index('idx_payment_patient_date')
        batch_op.drop_index('idx_payment_method')
        batch_op.drop_index('idx_payment_invoice_created')

    op.drop_table('payments')
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_results_updated_at'))
        batch_op.drop_index(batch_op.f('ix_lab_results_test_code'))
        batch_op.drop_index(batch_op.f('ix_lab_results_status'))
        batch_op.drop_index(batch_op.f('ix_lab_results_request_id'))
        batch_op.drop_index(batch_op.f('ix_lab_results_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_results_created_at'))

    op.drop_table('lab_results')
    with op.batch_alter_table('invoice_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_services_visit_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_services_service_code'))
        batch_op.drop_index(batch_op.f('ix_invoice_services_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_services_department_id'))

    op.drop_table('invoice_services')
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_claims_visit_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_updated_at'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_status'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_created_at'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_company_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_claim_number'))

    op.drop_table('insurance_claims')
    op.drop_table('vital_signs')
    op.drop_table('report_executions')
    with op.batch_alter_table('radiology_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radiology_requests_visit_id'))
        batch_op.drop_index(batch_op.f('ix_radiology_requests_updated_at'))
        batch_op.drop_index(batch_op.f('ix_radiology_requests_status'))
        batch_op.drop_index(batch_op.f('ix_radiology_requests_request_number'))
        batch_op.drop_index(batch_op.f('ix_radiology_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_radiology_requests_created_at'))

    op.drop_table('radiology_requests')
    op.drop_table('queue_management')
    op.drop_table('pricing_management')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_prescription_visit')
        batch_op.drop_index('idx_prescription_status')
        batch_op.drop_index('idx_prescription_patient')
        batch_op.drop_index('idx_prescription_number')
        batch_op.drop_index('idx_prescription_doctor')

    op.drop_table('prescriptions')
    op.drop_table('online_booking_payment_transactions')
    op.drop_table('notification_queue')
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_reports_visit_id'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_updated_at'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_created_at'))

    op.drop_table('medical_reports')
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_requests_visit_id'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_updated_at'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_status'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_request_number'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_created_at'))

    op.drop_table('lab_requests')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_visit_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_updated_at'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_created_at'))
        batch_op.drop_index('idx_invoice_status')

    op.drop_table('invoices')
    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_cases_updated_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_cases_status'))
        batch_op.drop_index(batch_op.f('ix_emergency_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_cases_completed_at'))

    op.drop_table('emergency_cases')
    with op.batch_alter_table('backup_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_backup_log_type')
        batch_op.drop_index('idx_backup_log_created')
        batch_op.drop_index('idx_backup_log_backup')

    op.drop_table('backup_logs')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_updated_at'))
        batch_op.drop_index(batch_op.f('ix_visits_status'))
        batch_op.drop_index(batch_op.f('ix_visits_payment_status'))
        batch_op.drop_index(batch_op.f('ix_visits_patient_id'))
        batch_op.drop_index(batch_op.f('ix_visits_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_visits_department_id'))
        batch_op.drop_index(batch_op.f('ix_visits_created_by'))
        batch_op.drop_index(batch_op.f('ix_visits_created_at'))
        batch_op.drop_index('idx_visit_patient_created')
        batch_op.drop_index('idx_visit_doctor_status')
        batch_op.drop_index('idx_visit_department_status')

    op.drop_table('visits')
    op.drop_table('user_permissions')
    with op.batch_alter_table('temporary_services', schema=None) as batch_op:
        batch_op.drop_index('idx_temporary_service_name')
        batch_op.drop_index('idx_temporary_service_active')

    op.drop_table('temporary_services')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_log_user')
        batch_op.drop_index('idx_log_level')
        batch_op.drop_index('idx_log_created')
        batch_op.drop_index('idx_log_category')

    op.drop_table('system_logs')
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index('idx_config_system')
        batch_op.drop_index('idx_config_key')
        batch_op.drop_index('idx_config_category')

    op.drop_table('system_configs')
    with op.batch_alter_table('service_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_master_updated_at'))
        batch_op.drop_index(batch_op.f('ix_service_master_is_active'))
        batch_op.drop_index(batch_op.f('ix_service_master_department_id'))
        batch_op.drop_index(batch_op.f('ix_service_master_created_at'))
        batch_op.drop_index(batch_op.f('ix_service_master_code'))

    op.drop_table('service_master')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index('idx_security_user')
        batch_op.drop_index('idx_security_severity')
        batch_op.drop_index('idx_security_resolved')
        batch_op.drop_index('idx_security_event_type')
        batch_op.drop_index('idx_security_created')

    op.drop_table('security_events')
    op.drop_table('role_permissions')
    op.drop_table('reports')
    op.drop_table('report_templates')
    op.drop_table('queue_settings')
    op.drop_table('pricing_rules')
    with op.batch_alter_table('pricing_catalog', schema=None) as batch_op:
        batch_op.drop_index('idx_pricing_temporary')
        batch_op.drop_index('idx_pricing_service_type')
        batch_op.drop_index('idx_pricing_active')

    op.drop_table('pricing_catalog')
    with op.batch_alter_table('patient_visit_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_visit_counters_updated_at'))
        batch_op.drop_index(batch_op.f('ix_patient_visit_counters_patient_id'))

    op.drop_table('patient_visit_counters')
    op.drop_table('online_bookings')
    op.drop_table('nurses')
    op.drop_table('notifications')
    op.drop_table('notification_templates')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_updated_at'))
        batch_op.drop_index(batch_op.f('ix_medical_records_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_created_at'))

    op.drop_table('medical_records')
    with op.batch_alter_table('doctor_pricing', schema=None) as batch_op:
        batch_op.drop_index('idx_doctor_pricing_effective')
        batch_op.drop_index('idx_doctor_pricing_doctor')
        batch_op.drop_index('idx_doctor_pricing_department')
        batch_op.drop_index('idx_doctor_pricing_active')

    op.drop_table('doctor_pricing')
    op.drop_table('branding_settings')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index('idx_backup_type')
        batch_op.drop_index('idx_backup_status')
        batch_op.drop_index('idx_backup_scheduled')
        batch_op.drop_index('idx_backup_name')
        batch_op.drop_index('idx_backup_created')

    op.drop_table('backups')
    with op.batch_alter_table('audit_trails', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_entity')
        batch_op.drop_index('idx_audit_created')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_trails')
    op.drop_table('audit_logs')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_starts_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_department_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_created_at'))
        batch_op.drop_index('idx_appt_doctor_time')

    op.drop_table('appointments')
    op.drop_table('whatsapp_messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_department_id'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index('idx_user_role')

    op.drop_table('users')
    op.drop_table('system_themes')
    with op.batch_alter_table('service_prices', schema=None) as batch_op:
        batch_op.drop_index('idx_service_type')
        batch_op.drop_index('idx_service_name')
        batch_op.drop_index('idx_service_effective')
        batch_op.drop_index('idx_service_code')
        batch_op.drop_index('idx_service_active')

    op.drop_table('service_prices')
    op.drop_table('roles')
    op.drop_table('permissions')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_updated_at'))
        batch_op.drop_index(batch_op.f('ix_patients_national_id'))
        batch_op.drop_index(batch_op.f('ix_patients_last_name'))
        batch_op.drop_index(batch_op.f('ix_patients_first_name'))
        batch_op.drop_index(batch_op.f('ix_patients_created_at'))
        batch_op.drop_index('idx_patient_name')

    op.drop_table('patients')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index('idx_medication_trade_name')
        batch_op.drop_index('idx_medication_generic_name')
        batch_op.drop_index('idx_medication_active')

    op.drop_table('medications')
    with op.batch_alter_table('insurance_providers', schema=None) as batch_op:
        batch_op.drop_index('idx_insurance_name_ar')
        batch_op.drop_index('idx_insurance_name')
        batch_op.drop_index('idx_insurance_code')
        batch_op.drop_index('idx_insurance_active')

    op.drop_table('insurance_providers')
    with op.batch_alter_table('insurance_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_companies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_insurance_companies_name'))
        batch_op.drop_index(batch_op.f('ix_insurance_companies_created_at'))

    op.drop_table('insurance_companies')
    op.drop_table('email_messages')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_departments_head_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_departments_created_at'))
        batch_op.drop_index('idx_department_name_ar')
        batch_op.drop_index('idx_department_active')

    op.drop_table('departments')
    # ### end Alembic commands ###
