"""Add index=True to all FK columns

Revision ID: add_fk_index_20260619
Revises: 1585c11601e4
Create Date: 2026-06-19

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_fk_index_20260619'
down_revision = '1585c11601e4'
branch_labels = None
depends_on = None


def upgrade():
    # Add index=True to all FK columns
    # Total indexes added: 320
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_imaging_analyses_patient_id" ON "ai_imaging_analyses" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_imaging_analyses_reviewed_by" ON "ai_imaging_analyses" ("reviewed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_imaging_analyses_series_id" ON "ai_imaging_analyses" ("series_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_imaging_analyses_study_id" ON "ai_imaging_analyses" ("study_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_recommendations_accepted_by" ON "ai_recommendations" ("accepted_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_recommendations_acknowledged_by" ON "ai_recommendations" ("acknowledged_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_recommendations_doctor_id" ON "ai_recommendations" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_recommendations_patient_id" ON "ai_recommendations" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_ai_recommendations_visit_id" ON "ai_recommendations" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_appointments_created_by" ON "appointments" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_appointments_department_id" ON "appointments" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_appointments_doctor_id" ON "appointments" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_appointments_patient_id" ON "appointments" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_appointments_tenant_id" ON "appointments" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_audit_trails_created_by" ON "audit_trails" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_audit_trails_report_id" ON "audit_trails" ("report_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_audit_trails_resolved_by" ON "audit_trails" ("resolved_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_audit_trails_user_id" ON "audit_trails" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_backup_restore_logs_backup_id" ON "backup_restore_logs" ("backup_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_backup_restore_logs_initiated_by" ON "backup_restore_logs" ("initiated_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_backups_backup_id" ON "backups" ("backup_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_backups_created_by" ON "backups" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_backups_last_restore_by" ON "backups" ("last_restore_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_barcode_registry_barcode_registry_id" ON "barcode_registry" ("barcode_registry_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_barcode_registry_generated_by_id" ON "barcode_registry" ("generated_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_barcode_registry_scanned_by_id" ON "barcode_registry" ("scanned_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_biometric_credentials_user_id" ON "biometric_credentials" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_branding_settings_created_by" ON "branding_settings" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_branding_settings_updated_by" ON "branding_settings" ("updated_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_budgets_created_by" ON "budgets" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_budgets_department_id" ON "budgets" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_cash_registers_receptionist_id" ON "cash_registers" ("receptionist_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_cds_alert_rules_acknowledged_by_id" ON "cds_alert_rules" ("acknowledged_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_cds_alert_rules_override_by_id" ON "cds_alert_rules" ("override_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_cds_alert_rules_patient_id" ON "cds_alert_rules" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_cds_alert_rules_prescription_id" ON "cds_alert_rules" ("prescription_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_cds_alert_rules_rule_id" ON "cds_alert_rules" ("rule_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_cds_alert_rules_visit_id" ON "cds_alert_rules" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_admission_id" ON "clinical_pathways" ("admission_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_assigned_by_id" ON "clinical_pathways" ("assigned_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_assigned_to_id" ON "clinical_pathways" ("assigned_to_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_care_plan_id" ON "clinical_pathways" ("care_plan_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_completed_by_id" ON "clinical_pathways" ("completed_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_created_by_id" ON "clinical_pathways" ("created_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_icd10_code_id" ON "clinical_pathways" ("icd10_code_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_pathway_id" ON "clinical_pathways" ("pathway_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_patient_id" ON "clinical_pathways" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_clinical_pathways_visit_id" ON "clinical_pathways" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dental_charts_chart_id" ON "dental_charts" ("chart_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dental_charts_doctor_id" ON "dental_charts" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dental_charts_patient_id" ON "dental_charts" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dental_charts_visit_id" ON "dental_charts" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_departments_head_doctor_id" ON "departments" ("head_doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_departments_tenant_id" ON "departments" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dicom_studies_patient_id" ON "dicom_studies" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dicom_studies_radiology_request_id" ON "dicom_studies" ("radiology_request_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dicom_studies_reviewed_by_id" ON "dicom_studies" ("reviewed_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dicom_studies_series_id" ON "dicom_studies" ("series_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_dicom_studies_study_id" ON "dicom_studies" ("study_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_digital_signatures_tenant_id" ON "digital_signatures" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_digital_signatures_user_id" ON "digital_signatures" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_disease_registries_icd10_code_id" ON "disease_registries" ("icd10_code_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_disease_registries_patient_id" ON "disease_registries" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_disease_registries_reported_by_id" ON "disease_registries" ("reported_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_drug_interactions_created_by" ON "drug_interactions" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_drug_interactions_medication_a_id" ON "drug_interactions" ("medication_a_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_drug_interactions_medication_b_id" ON "drug_interactions" ("medication_b_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emar_administrations_medication_id" ON "emar_administrations" ("medication_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emar_administrations_nurse_id" ON "emar_administrations" ("nurse_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emar_administrations_patient_id" ON "emar_administrations" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emar_administrations_prescription_id" ON "emar_administrations" ("prescription_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emar_administrations_prescription_item_id" ON "emar_administrations" ("prescription_item_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emar_administrations_visit_id" ON "emar_administrations" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emar_administrations_witnessed_by_id" ON "emar_administrations" ("witnessed_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emergency_cases_patient_id" ON "emergency_cases" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emergency_cases_tenant_id" ON "emergency_cases" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emergency_cases_visit_id" ON "emergency_cases" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emergency_status_history_changed_by" ON "emergency_status_history" ("changed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_emergency_status_history_emergency_id" ON "emergency_status_history" ("emergency_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_exchange_rates_created_by" ON "exchange_rates" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_fhir_patients_internal_file_id" ON "fhir_patients" ("internal_file_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_fhir_patients_internal_patient_id" ON "fhir_patients" ("internal_patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_fhir_patients_user_id" ON "fhir_patients" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_file_uploads_created_by" ON "file_uploads" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_file_uploads_file_id" ON "file_uploads" ("file_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_file_uploads_granted_by" ON "file_uploads" ("granted_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_file_uploads_tenant_id" ON "file_uploads" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_file_uploads_uploaded_by" ON "file_uploads" ("uploaded_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_file_uploads_user_id" ON "file_uploads" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_follow_up_requests_appointment_id" ON "follow_up_requests" ("appointment_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_follow_up_requests_created_by" ON "follow_up_requests" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_follow_up_requests_doctor_id" ON "follow_up_requests" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_follow_up_requests_patient_id" ON "follow_up_requests" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_follow_up_requests_source_visit_id" ON "follow_up_requests" ("source_visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_icd10_codes_coded_by_id" ON "icd10_codes" ("coded_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_icd10_codes_cpt_code_id" ON "icd10_codes" ("cpt_code_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_icd10_codes_icd10_code_id" ON "icd10_codes" ("icd10_code_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_icd10_codes_medical_record_id" ON "icd10_codes" ("medical_record_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_icd10_codes_patient_id" ON "icd10_codes" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_icd10_codes_visit_id" ON "icd10_codes" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_insurance_companies_company_id" ON "insurance_companies" ("company_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_insurance_companies_invoice_id" ON "insurance_companies" ("invoice_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_insurance_companies_visit_id" ON "insurance_companies" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_invoices_created_by" ON "invoices" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_invoices_department_id" ON "invoices" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_invoices_invoice_id" ON "invoices" ("invoice_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_invoices_tenant_id" ON "invoices" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_invoices_visit_id" ON "invoices" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_lab_quality_control_entries_recorded_by" ON "lab_quality_control_entries" ("recorded_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_lab_requests_patient_id" ON "lab_requests" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_lab_requests_performed_by" ON "lab_requests" ("performed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_lab_requests_request_id" ON "lab_requests" ("request_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_lab_requests_requested_by" ON "lab_requests" ("requested_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_lab_requests_tenant_id" ON "lab_requests" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_lab_requests_visit_id" ON "lab_requests" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medical_records_created_by" ON "medical_records" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medical_records_patient_id" ON "medical_records" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medical_records_visit_id" ON "medical_records" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medical_reports_signed_by" ON "medical_reports" ("signed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medical_reports_visit_id" ON "medical_reports" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_reconciliations_admission_id" ON "medication_reconciliations" ("admission_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_reconciliations_patient_id" ON "medication_reconciliations" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_reconciliations_reconciled_by_id" ON "medication_reconciliations" ("reconciled_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_reconciliations_visit_id" ON "medication_reconciliations" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_supply_requests_approved_by" ON "medication_supply_requests" ("approved_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_supply_requests_created_by" ON "medication_supply_requests" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_supply_requests_fulfilled_by" ON "medication_supply_requests" ("fulfilled_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_supply_requests_medication_id" ON "medication_supply_requests" ("medication_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medication_supply_requests_request_id" ON "medication_supply_requests" ("request_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_created_by" ON "medications" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_dispensed_by" ON "medications" ("dispensed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_doctor_id" ON "medications" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_medication_id" ON "medications" ("medication_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_patient_id" ON "medications" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_prescription_id" ON "medications" ("prescription_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_returned_by" ON "medications" ("returned_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_sale_id" ON "medications" ("sale_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_sale_item_id" ON "medications" ("sale_item_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_tenant_id" ON "medications" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_medications_visit_id" ON "medications" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_module_permissions_department_id" ON "module_permissions" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_module_permissions_role_id" ON "module_permissions" ("role_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_notifications_created_by" ON "notifications" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_notifications_recipient_department_id" ON "notifications" ("recipient_department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_notifications_recipient_id" ON "notifications" ("recipient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_notifications_sender_id" ON "notifications" ("sender_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_notifications_template_id" ON "notifications" ("template_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_notifications_tenant_id" ON "notifications" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_notifications_user_id" ON "notifications" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nurses_medication_id" ON "nurses" ("medication_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nurses_nurse_id" ON "nurses" ("nurse_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nurses_patient_id" ON "nurses" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nurses_prescription_id" ON "nurses" ("prescription_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nurses_prescription_item_id" ON "nurses" ("prescription_item_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nurses_tenant_id" ON "nurses" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nurses_user_id" ON "nurses" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nurses_visit_id" ON "nurses" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nursing_assessments_nurse_id" ON "nursing_assessments" ("nurse_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nursing_assessments_patient_id" ON "nursing_assessments" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_nursing_assessments_visit_id" ON "nursing_assessments" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_online_bookings_booking_id" ON "online_bookings" ("booking_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_online_bookings_department_id" ON "online_bookings" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_online_bookings_doctor_id" ON "online_bookings" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_online_bookings_patient_id" ON "online_bookings" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_online_bookings_tenant_id" ON "online_bookings" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_accounts_patient_id" ON "patient_accounts" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_accounts_user_id" ON "patient_accounts" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_education_materials_assigned_by" ON "patient_education_materials" ("assigned_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_education_materials_created_by" ON "patient_education_materials" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_education_materials_material_id" ON "patient_education_materials" ("material_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_education_materials_patient_id" ON "patient_education_materials" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_problems_icd10_code_id" ON "patient_problems" ("icd10_code_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_problems_patient_id" ON "patient_problems" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_problems_recorded_by_id" ON "patient_problems" ("recorded_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_problems_reported_by_id" ON "patient_problems" ("reported_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_satisfaction_surveys_patient_id" ON "patient_satisfaction_surveys" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_satisfaction_surveys_visit_id" ON "patient_satisfaction_surveys" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patient_visit_counters_patient_id" ON "patient_visit_counters" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patients_insurance_company_id" ON "patients" ("insurance_company_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patients_patient_id" ON "patients" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_patients_tenant_id" ON "patients" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_payments_cancelled_by" ON "payments" ("cancelled_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_payments_invoice_id" ON "payments" ("invoice_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_payments_patient_id" ON "payments" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_payments_received_by" ON "payments" ("received_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_payments_tenant_id" ON "payments" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_payments_visit_id" ON "payments" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_permissions_granted_by" ON "permissions" ("granted_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_permissions_permission_id" ON "permissions" ("permission_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_permissions_role_id" ON "permissions" ("role_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_permissions_user_id" ON "permissions" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_pricing_management_created_by" ON "pricing_management" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_pricing_management_department_id" ON "pricing_management" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_pricing_management_service_id" ON "pricing_management" ("service_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_queue_management_department_id" ON "queue_management" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_queue_management_emergency_approved_by" ON "queue_management" ("emergency_approved_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_queue_management_force_entry_approved_by" ON "queue_management" ("force_entry_approved_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_queue_management_patient_id" ON "queue_management" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_queue_management_tenant_id" ON "queue_management" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_queue_management_visit_id" ON "queue_management" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_requests_patient_id" ON "radiology_requests" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_requests_requested_by" ON "radiology_requests" ("requested_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_requests_tenant_id" ON "radiology_requests" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_requests_visit_id" ON "radiology_requests" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_results_patient_id" ON "radiology_results" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_results_performed_by" ON "radiology_results" ("performed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_results_request_id" ON "radiology_results" ("request_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_results_reviewed_by" ON "radiology_results" ("reviewed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_radiology_results_tenant_id" ON "radiology_results" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_receipts_created_by" ON "receipts" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_receipts_debt_approved_by" ON "receipts" ("debt_approved_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_receipts_patient_id" ON "receipts" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_receipts_printed_by" ON "receipts" ("printed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_receipts_visit_id" ON "receipts" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_referrals_created_by_id" ON "referrals" ("created_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_referrals_patient_id" ON "referrals" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_referrals_referring_doctor_id" ON "referrals" ("referring_doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_referrals_visit_id" ON "referrals" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_reports_created_by" ON "reports" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_reports_executed_by" ON "reports" ("executed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_reports_report_id" ON "reports" ("report_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_reports_tenant_id" ON "reports" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_request_workflows_user_id" ON "request_workflows" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_service_master_department_id" ON "service_master" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_service_master_tenant_id" ON "service_master" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_service_prices_created_by" ON "service_prices" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_service_prices_department_id" ON "service_prices" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_service_prices_doctor_id" ON "service_prices" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_sso_configurations_default_department_id" ON "sso_configurations" ("default_department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_sso_configurations_sso_config_id" ON "sso_configurations" ("sso_config_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_sso_configurations_user_id" ON "sso_configurations" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_admission_id" ON "surgery_schedules" ("admission_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_anesthesiologist_id" ON "surgery_schedules" ("anesthesiologist_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_assistant_surgeon_id" ON "surgery_schedules" ("assistant_surgeon_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_circulating_nurse_id" ON "surgery_schedules" ("circulating_nurse_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_completed_by_id" ON "surgery_schedules" ("completed_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_cpt_code_id" ON "surgery_schedules" ("cpt_code_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_created_by_id" ON "surgery_schedules" ("created_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_icd10_code_id" ON "surgery_schedules" ("icd10_code_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_patient_id" ON "surgery_schedules" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_scrub_nurse_id" ON "surgery_schedules" ("scrub_nurse_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_surgeon_id" ON "surgery_schedules" ("surgeon_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_surgery_schedule_id" ON "surgery_schedules" ("surgery_schedule_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_surgery_schedules_visit_id" ON "surgery_schedules" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_system_configs_created_by" ON "system_configs" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_system_configs_updated_by" ON "system_configs" ("updated_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_added_by" ON "tasks" ("added_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_assigned_by" ON "tasks" ("assigned_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_assigned_to" ON "tasks" ("assigned_to")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_attached_by" ON "tasks" ("attached_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_created_by" ON "tasks" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_file_id" ON "tasks" ("file_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_project_id" ON "tasks" ("project_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_project_manager" ON "tasks" ("project_manager")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_task_id" ON "tasks" ("task_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_tenant_id" ON "tasks" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_tasks_user_id" ON "tasks" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_telemedicine_appointments_appointment_id" ON "telemedicine_appointments" ("appointment_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_telemedicine_appointments_created_by" ON "telemedicine_appointments" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_telemedicine_appointments_doctor_id" ON "telemedicine_appointments" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_telemedicine_appointments_patient_id" ON "telemedicine_appointments" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_telemedicine_appointments_visit_id" ON "telemedicine_appointments" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_treatments_doctor_id" ON "treatments" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_treatments_visit_id" ON "treatments" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_user_department_access_department_id" ON "user_department_access" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_user_department_access_user_id" ON "user_department_access" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_user_mfa_settings_user_id" ON "user_mfa_settings" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_users_department_id" ON "users" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_users_tenant_id" ON "users" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_users_user_id" ON "users" ("user_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_vaccines_administered_by_id" ON "vaccines" ("administered_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_vaccines_patient_id" ON "vaccines" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_vaccines_vaccine_id" ON "vaccines" ("vaccine_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visit_transfer_logs_from_department_id" ON "visit_transfer_logs" ("from_department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visit_transfer_logs_from_doctor_id" ON "visit_transfer_logs" ("from_doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visit_transfer_logs_to_department_id" ON "visit_transfer_logs" ("to_department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visit_transfer_logs_to_doctor_id" ON "visit_transfer_logs" ("to_doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visit_transfer_logs_transferred_by" ON "visit_transfer_logs" ("transferred_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visit_transfer_logs_visit_id" ON "visit_transfer_logs" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_archived_by" ON "visits" ("archived_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_completed_by" ON "visits" ("completed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_created_by" ON "visits" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_department_id" ON "visits" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_doctor_id" ON "visits" ("doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_force_payment_approved_by" ON "visits" ("force_payment_approved_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_insurance_company_id" ON "visits" ("insurance_company_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_patient_id" ON "visits" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_receipt_printed_by" ON "visits" ("receipt_printed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_visits_tenant_id" ON "visits" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_admission_id" ON "wards" ("admission_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_admitting_doctor_id" ON "wards" ("admitting_doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_approved_by_id" ON "wards" ("approved_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_attending_doctor_id" ON "wards" ("attending_doctor_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_bed_id" ON "wards" ("bed_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_current_patient_id" ON "wards" ("current_patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_department_id" ON "wards" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_drg_code_id" ON "wards" ("drg_code_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_from_bed_id" ON "wards" ("from_bed_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_patient_id" ON "wards" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_requested_by_id" ON "wards" ("requested_by_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_room_id" ON "wards" ("room_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_to_bed_id" ON "wards" ("to_bed_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_visit_id" ON "wards" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_wards_ward_id" ON "wards" ("ward_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_what_if_scenarios_created_by" ON "what_if_scenarios" ("created_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_what_if_scenarios_param_department_id" ON "what_if_scenarios" ("param_department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_whatsapp_integration_messages_patient_id" ON "whatsapp_integration_messages" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_whatsapp_integration_messages_sent_by" ON "whatsapp_integration_messages" ("sent_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_appointment_id" ON "workflow_steps" ("appointment_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_current_step_id" ON "workflow_steps" ("current_step_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_department_id" ON "workflow_steps" ("department_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_from_step_id" ON "workflow_steps" ("from_step_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_patient_id" ON "workflow_steps" ("patient_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_performed_by" ON "workflow_steps" ("performed_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_step_id" ON "workflow_steps" ("step_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_tenant_id" ON "workflow_steps" ("tenant_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_to_step_id" ON "workflow_steps" ("to_step_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_transferred_by" ON "workflow_steps" ("transferred_by")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_visit_id" ON "workflow_steps" ("visit_id")')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_workflow_steps_workflow_id" ON "workflow_steps" ("workflow_id")')


def downgrade():
    # Remove FK indexes
    op.execute('DROP INDEX IF EXISTS "ix_ai_imaging_analyses_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_imaging_analyses_reviewed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_imaging_analyses_series_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_imaging_analyses_study_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_accepted_by"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_acknowledged_by"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_audit_trails_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_audit_trails_report_id"')
    op.execute('DROP INDEX IF EXISTS "ix_audit_trails_resolved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_audit_trails_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_backup_restore_logs_backup_id"')
    op.execute('DROP INDEX IF EXISTS "ix_backup_restore_logs_initiated_by"')
    op.execute('DROP INDEX IF EXISTS "ix_backups_backup_id"')
    op.execute('DROP INDEX IF EXISTS "ix_backups_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_backups_last_restore_by"')
    op.execute('DROP INDEX IF EXISTS "ix_barcode_registry_barcode_registry_id"')
    op.execute('DROP INDEX IF EXISTS "ix_barcode_registry_generated_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_barcode_registry_scanned_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_biometric_credentials_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_branding_settings_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_branding_settings_updated_by"')
    op.execute('DROP INDEX IF EXISTS "ix_budgets_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_budgets_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cash_registers_receptionist_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_acknowledged_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_override_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_prescription_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_rule_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_admission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_assigned_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_assigned_to_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_care_plan_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_completed_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_created_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_pathway_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dental_charts_chart_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dental_charts_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dental_charts_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dental_charts_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_departments_head_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_departments_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_radiology_request_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_reviewed_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_series_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_study_id"')
    op.execute('DROP INDEX IF EXISTS "ix_digital_signatures_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_digital_signatures_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_disease_registries_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_disease_registries_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_disease_registries_reported_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_drug_interactions_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_drug_interactions_medication_a_id"')
    op.execute('DROP INDEX IF EXISTS "ix_drug_interactions_medication_b_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_medication_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_prescription_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_prescription_item_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_witnessed_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_cases_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_cases_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_cases_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_status_history_changed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_status_history_emergency_id"')
    op.execute('DROP INDEX IF EXISTS "ix_exchange_rates_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_fhir_patients_internal_file_id"')
    op.execute('DROP INDEX IF EXISTS "ix_fhir_patients_internal_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_fhir_patients_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_file_id"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_granted_by"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_uploaded_by"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_appointment_id"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_source_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_coded_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_cpt_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_medical_record_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_insurance_companies_company_id"')
    op.execute('DROP INDEX IF EXISTS "ix_insurance_companies_invoice_id"')
    op.execute('DROP INDEX IF EXISTS "ix_insurance_companies_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_invoice_id"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_quality_control_entries_recorded_by"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_performed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_request_id"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_requested_by"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_records_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_records_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_records_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_reports_signed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_reports_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_reconciliations_admission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_reconciliations_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_reconciliations_reconciled_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_reconciliations_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_fulfilled_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_medication_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_request_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_dispensed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_medication_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_prescription_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_returned_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_sale_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_sale_item_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_module_permissions_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_module_permissions_role_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_recipient_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_recipient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_sender_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_template_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_medication_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_prescription_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_prescription_item_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nursing_assessments_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nursing_assessments_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nursing_assessments_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_booking_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_accounts_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_accounts_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_education_materials_assigned_by"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_education_materials_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_education_materials_material_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_education_materials_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_problems_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_problems_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_problems_recorded_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_problems_reported_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_satisfaction_surveys_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_satisfaction_surveys_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_visit_counters_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patients_insurance_company_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patients_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patients_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_cancelled_by"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_invoice_id"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_received_by"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_permissions_granted_by"')
    op.execute('DROP INDEX IF EXISTS "ix_permissions_permission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_permissions_role_id"')
    op.execute('DROP INDEX IF EXISTS "ix_permissions_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_pricing_management_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_pricing_management_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_pricing_management_service_id"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_emergency_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_force_entry_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_requests_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_requests_requested_by"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_requests_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_requests_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_performed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_request_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_reviewed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_debt_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_printed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_referrals_created_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_referrals_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_referrals_referring_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_referrals_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_reports_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_reports_executed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_reports_report_id"')
    op.execute('DROP INDEX IF EXISTS "ix_reports_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_request_workflows_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_service_master_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_service_master_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_service_prices_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_service_prices_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_service_prices_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_sso_configurations_default_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_sso_configurations_sso_config_id"')
    op.execute('DROP INDEX IF EXISTS "ix_sso_configurations_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_admission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_anesthesiologist_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_assistant_surgeon_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_circulating_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_completed_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_cpt_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_created_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_scrub_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_surgeon_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_surgery_schedule_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_system_configs_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_system_configs_updated_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_added_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_assigned_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_assigned_to"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_attached_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_file_id"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_project_id"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_project_manager"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_task_id"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_appointment_id"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_treatments_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_treatments_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_user_department_access_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_user_department_access_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_user_mfa_settings_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_users_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_users_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_users_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_vaccines_administered_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_vaccines_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_vaccines_vaccine_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_from_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_from_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_to_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_to_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_transferred_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_archived_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_completed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_force_payment_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_insurance_company_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_receipt_printed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_admission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_admitting_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_approved_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_attending_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_bed_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_current_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_drg_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_from_bed_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_requested_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_room_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_to_bed_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_ward_id"')
    op.execute('DROP INDEX IF EXISTS "ix_what_if_scenarios_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_what_if_scenarios_param_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_whatsapp_integration_messages_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_whatsapp_integration_messages_sent_by"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_appointment_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_current_step_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_from_step_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_performed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_step_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_to_step_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_transferred_by"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_workflow_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_imaging_analyses_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_imaging_analyses_reviewed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_imaging_analyses_series_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_imaging_analyses_study_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_accepted_by"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_acknowledged_by"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_ai_recommendations_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_appointments_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_audit_trails_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_audit_trails_report_id"')
    op.execute('DROP INDEX IF EXISTS "ix_audit_trails_resolved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_audit_trails_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_backup_restore_logs_backup_id"')
    op.execute('DROP INDEX IF EXISTS "ix_backup_restore_logs_initiated_by"')
    op.execute('DROP INDEX IF EXISTS "ix_backups_backup_id"')
    op.execute('DROP INDEX IF EXISTS "ix_backups_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_backups_last_restore_by"')
    op.execute('DROP INDEX IF EXISTS "ix_barcode_registry_barcode_registry_id"')
    op.execute('DROP INDEX IF EXISTS "ix_barcode_registry_generated_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_barcode_registry_scanned_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_biometric_credentials_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_branding_settings_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_branding_settings_updated_by"')
    op.execute('DROP INDEX IF EXISTS "ix_budgets_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_budgets_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cash_registers_receptionist_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_acknowledged_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_override_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_prescription_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_rule_id"')
    op.execute('DROP INDEX IF EXISTS "ix_cds_alert_rules_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_admission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_assigned_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_assigned_to_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_care_plan_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_completed_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_created_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_pathway_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_clinical_pathways_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dental_charts_chart_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dental_charts_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dental_charts_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dental_charts_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_departments_head_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_departments_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_radiology_request_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_reviewed_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_series_id"')
    op.execute('DROP INDEX IF EXISTS "ix_dicom_studies_study_id"')
    op.execute('DROP INDEX IF EXISTS "ix_digital_signatures_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_digital_signatures_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_disease_registries_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_disease_registries_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_disease_registries_reported_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_drug_interactions_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_drug_interactions_medication_a_id"')
    op.execute('DROP INDEX IF EXISTS "ix_drug_interactions_medication_b_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_medication_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_prescription_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_prescription_item_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emar_administrations_witnessed_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_cases_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_cases_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_cases_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_status_history_changed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_emergency_status_history_emergency_id"')
    op.execute('DROP INDEX IF EXISTS "ix_exchange_rates_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_fhir_patients_internal_file_id"')
    op.execute('DROP INDEX IF EXISTS "ix_fhir_patients_internal_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_fhir_patients_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_file_id"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_granted_by"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_uploaded_by"')
    op.execute('DROP INDEX IF EXISTS "ix_file_uploads_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_appointment_id"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_follow_up_requests_source_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_coded_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_cpt_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_medical_record_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_icd10_codes_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_insurance_companies_company_id"')
    op.execute('DROP INDEX IF EXISTS "ix_insurance_companies_invoice_id"')
    op.execute('DROP INDEX IF EXISTS "ix_insurance_companies_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_invoice_id"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_invoices_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_quality_control_entries_recorded_by"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_performed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_request_id"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_requested_by"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_lab_requests_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_records_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_records_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_records_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_reports_signed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medical_reports_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_reconciliations_admission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_reconciliations_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_reconciliations_reconciled_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_reconciliations_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_fulfilled_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_medication_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medication_supply_requests_request_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_dispensed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_medication_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_prescription_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_returned_by"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_sale_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_sale_item_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_medications_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_module_permissions_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_module_permissions_role_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_recipient_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_recipient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_sender_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_template_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_notifications_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_medication_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_prescription_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_prescription_item_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nurses_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nursing_assessments_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nursing_assessments_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_nursing_assessments_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_booking_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_online_bookings_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_accounts_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_accounts_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_education_materials_assigned_by"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_education_materials_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_education_materials_material_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_education_materials_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_problems_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_problems_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_problems_recorded_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_problems_reported_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_satisfaction_surveys_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_satisfaction_surveys_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patient_visit_counters_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patients_insurance_company_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patients_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_patients_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_cancelled_by"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_invoice_id"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_received_by"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_payments_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_permissions_granted_by"')
    op.execute('DROP INDEX IF EXISTS "ix_permissions_permission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_permissions_role_id"')
    op.execute('DROP INDEX IF EXISTS "ix_permissions_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_pricing_management_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_pricing_management_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_pricing_management_service_id"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_emergency_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_force_entry_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_queue_management_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_requests_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_requests_requested_by"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_requests_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_requests_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_performed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_request_id"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_reviewed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_radiology_results_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_debt_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_printed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_receipts_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_referrals_created_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_referrals_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_referrals_referring_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_referrals_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_reports_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_reports_executed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_reports_report_id"')
    op.execute('DROP INDEX IF EXISTS "ix_reports_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_request_workflows_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_service_master_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_service_master_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_service_prices_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_service_prices_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_service_prices_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_sso_configurations_default_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_sso_configurations_sso_config_id"')
    op.execute('DROP INDEX IF EXISTS "ix_sso_configurations_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_admission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_anesthesiologist_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_assistant_surgeon_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_circulating_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_completed_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_cpt_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_created_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_icd10_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_scrub_nurse_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_surgeon_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_surgery_schedule_id"')
    op.execute('DROP INDEX IF EXISTS "ix_surgery_schedules_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_system_configs_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_system_configs_updated_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_added_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_assigned_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_assigned_to"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_attached_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_file_id"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_project_id"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_project_manager"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_task_id"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_tasks_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_appointment_id"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_telemedicine_appointments_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_treatments_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_treatments_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_user_department_access_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_user_department_access_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_user_mfa_settings_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_users_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_users_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_users_user_id"')
    op.execute('DROP INDEX IF EXISTS "ix_vaccines_administered_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_vaccines_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_vaccines_vaccine_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_from_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_from_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_to_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_to_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_transferred_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visit_transfer_logs_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_archived_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_completed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_force_payment_approved_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_insurance_company_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_receipt_printed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_visits_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_admission_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_admitting_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_approved_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_attending_doctor_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_bed_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_current_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_drg_code_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_from_bed_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_requested_by_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_room_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_to_bed_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_wards_ward_id"')
    op.execute('DROP INDEX IF EXISTS "ix_what_if_scenarios_created_by"')
    op.execute('DROP INDEX IF EXISTS "ix_what_if_scenarios_param_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_whatsapp_integration_messages_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_whatsapp_integration_messages_sent_by"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_appointment_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_current_step_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_department_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_from_step_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_patient_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_performed_by"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_step_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_tenant_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_to_step_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_transferred_by"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_visit_id"')
    op.execute('DROP INDEX IF EXISTS "ix_workflow_steps_workflow_id"')
